apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-db
  namespace: inventario
  labels:
    app: inventario-db
<<<<<<< HEAD
=======
    tier: database
>>>>>>> origin/desarrollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-db
  template:
    metadata:
      labels:
        app: inventario-db
<<<<<<< HEAD
    spec:
      containers:
        - name: inventario-db
          image: mongo:7
          ports:
            - containerPort: 27017
=======
        tier: database
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
              name: mongo
>>>>>>> origin/desarrollo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: inventario-db-secret
<<<<<<< HEAD
                  key: username
=======
                  key: MONGO_INITDB_ROOT_USERNAME
>>>>>>> origin/desarrollo
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventario-db-secret
<<<<<<< HEAD
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: "inventario_hardware"
          volumeMounts:
            - name: mongodata
              mountPath: /data/db
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: inventario-db-pvc
=======
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: inventario-db-pvc
>>>>>>> origin/desarrollo
