apiVersion: v1
kind: Service
metadata:
  name: inventario-db
  namespace: inventario
spec:
  type: ClusterIP
  selector:
    app: inventario-db
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
