apiVersion: v1
kind: Secret
metadata:
  name: inventario-db-secret
  namespace: inventario
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "Mongo_EGI_2026!"