apiVersion: v1
kind: Secret
metadata:
  name: inventario-db-secret
  namespace: inventario
type: Opaque
stringData:
  #Cambiar esto
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "ChangeMe_EGI_2025!"
