apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubicacion-db
  namespace: inventario
  labels:
    app: ubicacion-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubicacion-db
  template:
    metadata:
      labels:
        app: ubicacion-db
    spec:
      containers:
        - name: ubicacion-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ubicacion-db-secret
                  key: password
          volumeMounts:
            - name: sqldata
              mountPath: /var/opt/mssql
      volumes:
        - name: sqldata
          persistentVolumeClaim:
            claimName: ubicacion-db-pvc
