apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-service
  namespace: inventario
  labels:
    app: ldap-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-service
  template:
    metadata:
      labels:
        app: ldap-service
    spec:
      containers:
        - name: ldap-service
          image: osixia/openldap:1.5.0
          args: ["--copy-service"]
          ports:
            - containerPort: 389
            - containerPort: 636
          env:
            - name: LDAP_ORGANISATION
              value: "ITU Universidad"
            - name: LDAP_DOMAIN
              value: "itu.edu"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: admin-password
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
            - name: ldap-bootstrap
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: ldap-data-pvc
        - name: ldap-config
          persistentVolumeClaim:
            claimName: ldap-config-pvc
        - name: ldap-bootstrap
          configMap:
            name: ldap-bootstrap
